[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
preDeployCommand = ["python scripts/deploy.py"]
healthcheckPath = "/health/ready"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
